"""fase3: reservations + FKs diferidas

Revision ID: 3c6229bdbc98
Revises: 34440482b2c4
Create Date: 2026-06-20 06:16:37.501497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c6229bdbc98'
down_revision: Union[str, None] = '34440482b2c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('room_id', sa.UUID(), nullable=False),
    sa.Column('guest_name', sa.String(length=150), nullable=False),
    sa.Column('guest_phone', sa.String(length=20), nullable=True),
    sa.Column('check_in', sa.DateTime(timezone=True), nullable=False),
    sa.Column('check_out', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('pending', 'active', 'checked_out', 'cancelled', name='reservation_status'), server_default='pending', nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['rooms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'charges', 'reservations', ['reservation_id'], ['id'])
    op.create_foreign_key(None, 'cleaning_requests', 'reservations', ['reservation_id'], ['id'])
    op.create_foreign_key(None, 'minibar_consumptions', 'reservations', ['reservation_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'minibar_consumptions', type_='foreignkey')
    op.drop_constraint(None, 'cleaning_requests', type_='foreignkey')
    op.drop_constraint(None, 'charges', type_='foreignkey')
    op.drop_table('reservations')
    # ### end Alembic commands ###
