"""reservas publicas: source, confirmed, guest_email

Revision ID: 5f26edaa55dd
Revises: 548e40afaeb1
Create Date: 2026-06-23 04:30:35.321922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f26edaa55dd'
down_revision: Union[str, None] = '548e40afaeb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


reservation_source = sa.Enum('staff', 'website', name='reservation_source')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    reservation_source.create(op.get_bind())
    op.add_column('reservations', sa.Column('guest_email', sa.String(length=150), nullable=True))
    op.add_column('reservations', sa.Column('source', reservation_source, server_default='staff', nullable=False))
    op.add_column('reservations', sa.Column('confirmed', sa.Boolean(), server_default=sa.text('true'), nullable=False))
    op.alter_column('reservations', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reservations', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('reservations', 'confirmed')
    op.drop_column('reservations', 'source')
    op.drop_column('reservations', 'guest_email')
    reservation_source.drop(op.get_bind())
    # ### end Alembic commands ###
