"""fase3: guest_id_document en reservations

Revision ID: 684cea210451
Revises: 3c6229bdbc98
Create Date: 2026-06-20 07:01:16.828252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684cea210451'
down_revision: Union[str, None] = '3c6229bdbc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('guest_id_document', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'guest_id_document')
    # ### end Alembic commands ###
