"""reservas publicas: notes

Revision ID: 8160490a4546
Revises: 5f26edaa55dd
Create Date: 2026-06-23 04:37:07.294366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8160490a4546'
down_revision: Union[str, None] = '5f26edaa55dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservations', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservations', 'notes')
    # ### end Alembic commands ###
